use MovieExperience;

INSERT INTO Showing (Title, Room, showTime) values ('The Silence of the Lambs', 'Blue Laggon', 12/31/2020)

--Row 1
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 1, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 2, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 3, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 4, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 5, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 6, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 7, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 8, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 9, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 10, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 11, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (1, 12, 0, 1)

--Row 2
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 1, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 2, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 3, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 4, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 5, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 6, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 7, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 8, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 9, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 10, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 11, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (2, 12, 0, 1)

--Row 3
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 1, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 2, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 3, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 4, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 5, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 6, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 7, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 8, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 9, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 10, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 11, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (3, 12, 0, 1)

--Row 4
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 1, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 2, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 3, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 4, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 5, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 6, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 7, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 8, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 9, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 10, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 11, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (4, 12, 0, 1)

--Row 5
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 1, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 2, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 3, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 4, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 5, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 6, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 7, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 8, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 9, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 10, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 11, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (5, 12, 0, 1)

--Row 6
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 1, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 2, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 3, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 4, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 5, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 6, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 7, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 8, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 9, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 10, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 11, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (6, 12, 0, 1)

--Row 7
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 1, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 2, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 3, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 4, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 5, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 6, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 7, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 8, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 9, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 10, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 11, 0, 1)
INSERT INTO SeatReservation (seatRow, seatNo, reserved, showing_id) values (7, 12, 0, 1)

