

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using Foolproof;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.Tickets = new HashSet<Ticket>();
        }

        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string DeparturePlace { get; set; }
        [Required]
        public string ArrivalPlace { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public System.DateTime DepartureDate { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [GreaterThan("DepartureDate")]
        public System.DateTime ArrivalDate { get; set; }
        [Required]
        public string UserId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }

        public Trip(string name, string description, string departurePlace, string arrivalPlace, DateTime departureDate, DateTime arrivalDate, string userId)
        {
            Name = name;
            Description = description;
            DeparturePlace = departurePlace;
            ArrivalPlace = arrivalPlace;
            DepartureDate = departureDate;
            ArrivalDate = arrivalDate;
            UserId = userId;
        }
        public Trip(int id, string name, string description, string departurePlace, string arrivalPlace, DateTime departureDate, DateTime arrivalDate, string userId)
        {
            ID = id;
            Name = name;
            Description = description;
            DeparturePlace = departurePlace;
            ArrivalPlace = arrivalPlace;
            DepartureDate = departureDate;
            ArrivalDate = arrivalDate;
            UserId = userId;
        }
    }
}